### PR TITLE
Modernise project

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@foutaise you should probably consider dropping support for python <= 2.7

**Comment by graingert** [comment]
@foutaise when you merge this, it will need a release with "python setup.py sdist bdist_wheel upload"

**Comment by foutaise** [comment]
Hi Thomas,

Thanks for your pull request, and sorry for the late answer.

I took the time to study your PR, and I have to admit that I don't feel the need to modernize texttable. I appreciate your effort, but to be totally honest, when I look at the changes, I have the feeling that it would add more cruft to the project, and that's against my philosophy (*).

I want to keep this project as frugal as possible. Every line of code added is a line of code to maintain. I'm aware that I'm not using all the facilities available (travis, tox, bdist_wheel...), but I'm ok with that too.

So if I have a look at the points of your PR:
* add gitignore: never felt the need for a gitignore for such a small project. The one you provide is ~ 15% the size of the library.
* add tox.ini / travis: don't feel the need to use these external resources for a project of this size. I'm aware the project lacks tests right now. I might add some in the future if I really feel the need.
* fix setup.py: might remove reference to python < 2.2.3, for the rest, don't see the need for setuptools. distutils is part of the standard library and does the job for this library.
* changelog: adding a changelog might be a good point
* remove shebang: done
* remove line length override: I'm aware a few lines exceed 79 characters, the project is therefore not pep8 compliant. But what's the best: keeping the code simple, of using tricks to keep a few lines under 79 characters in order to please a pep? I prefer simplicity in the code.

I hope you'll understand my point of view. I'm aware that I may sound like an old grumpy guy. But as software is becoming more and more bloated nowadays, I like to keep mine stupid and simple.

Thanks again.

Regards,

(*) http://suckless.org/philosophy

**Comment by graingert** [comment]
While I agree with several of your points, I strongly disagree on some specific points:

* No tox: automated tests are applicable to a project of any size and allow contributors greater ease in which to make changes to this project
* No setuptools, setuptools is the new Python foundation blessed version of distutils. And it's a hard requirement for wheels (why I made these changes in the first place)
* README.rst  reStructuredText is the lingua franca of Python documentation. It's currently a hard requirement of readable presentable documentation on PyPI.

**Comment by graingert** [comment]
I originally made this PR to speed up my CI builds because a tool I depend on depends on this library. If this package and others switch to using wheels my CI builds will be much faster.

Wheels require the project to switch to setuptools.

**Pull request closed without merging**
